### GET ALL
GET http://localhost:3000/api/plantillaAnalisis

### POST
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/plantillaAnalisis
Content-Type: application/json

{
  "denominacion": "Salta",
  "codPostal": "3000"
}

### ID
@id = 4

### GET ONE 
GET http://localhost:3000/api/plantillaAnalisis/{{id}}

### PUT
PUT http://localhost:3000/api/plantillaAnalisis/{{id}}
Content-Type: application/json

{
  "denominacion": "Rosario",
  "codPostal": "2001"
}

### DELETE
DELETE http://localhost:3000/api/plantillaAnalisis/{{id}}
