### GET ALL
GET http://localhost:3000/api/paciente

### POST
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/paciente
Content-Type: application/json

{
  "nombre": "Santiago",
  "apellido": "Dedich",
  "dni": "12345678",
  "fechaNacimiento": "1990-01-01",
  "telefono": "123456789",
  "email": "santiago@example.com",
  "direccion": "Calle Falsa 123"
}

### ID
@id = 1

### GET ONE 
GET http://localhost:3000/api/paciente/{{id}}

### PUT
PUT http://localhost:3000/api/paciente/{{id}}
Content-Type: application/json

{
  "nombre": "Santiago",
  "apellido": "Dedich",
  "fechaNacimiento": "2003-11-13",
  "telefono": "3467494137",
  "direccion": "25 de Mayo 1256"
}

### DELETE
DELETE http://localhost:3000/api/paciente/{{id}}
