### GET ALL
GET http://localhost:3000/api/turno

### POST
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/turno   
Content-Type: application/json 

{
  "recibeMail": true,
  "estado": "Pendiente",
  "receta": "uploads/santi.png",
  "observacion": "-",
  "fechaHoraReserva": "2025-08-15",
  "paciente": 1,
  "centroAtencion": 1,
  "tipoAnalisis": 2
}

### ID
@id = 9

### GET ONE 
GET http://localhost:3000/api/turno/{{id}}

### PUT
PUT http://localhost:3000/api/turno/{{id}}
Content-Type: application/json

{
  "recibeMail": true
}

### DELETE
DELETE http://localhost:3000/api/turno/{{id}}
