### GET ALL
GET http://localhost:3000/api/turno

### POST
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/turno   
Content-Type: application/json 

{
  "recibeMail": false,
  "estado": "Pendiente",
  "observacion": "-",
  "fechaHoraExtraccion": "2025-07-27T00:00:00Z",
  "paciente": 1,
  "centroAtencion": 1,
  "tipoAnalisis": 2
}

### ID
@id = 4

### GET ONE 
GET http://localhost:3000/api/turno/{{id}}

### PUT
PUT http://localhost:3000/api/turno/{{id}}
Content-Type: application/json

{
  "recibeMail": true,
  "estado": "Completo",
  "receta": "Receta",
  "observacion": "S/Observaciones",
  "fechaHoraExtraccion": "2025-07-27T00:00:00Z",
  "paciente": 1,
  "centroAtencion": 1,
   "tipoAnalisis": 2
}

### DELETE
DELETE http://localhost:3000/api/turno/{{id}}
