### GET ALL
GET http://localhost:3000/api/turno

### FILTER
GET http://localhost:3000/api/turno/filter?estado=Pendiente

### POST
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/turno   
Content-Type: application/json 

{
  "recibeMail": true,
  "estado": "Pendiente",
  "receta": "uploads/santi.png",
  "observacion": "-",
  "fechaHoraReserva": "2025-08-15",
  "paciente": 1,
  "centroAtencion": 1,
  "tipoAnalisis": 1
}

### ID
@id = 14

### GET ONE 
GET http://localhost:3000/api/turno/{{id}}

### PUT
PUT http://localhost:3000/api/turno/{{id}}
Content-Type: application/json

{
"tipoAnalisis": 7
}

### DELETE
DELETE http://localhost:3000/api/turno/{{id}}
