### GET ALL
GET http://localhost:3000/api/localidad

### POST
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/localidad   
Content-Type: application/json 

{
  "denominacion": "Salta",
  "codPostal": "1500"
}

### ID
@id = 10

### GET ONE 
GET http://localhost:3000/api/localidad/{{id}}

### PUT
PUT http://localhost:3000/api/localidad/{{id}}
Content-Type: application/json

{
  "denominacion": "Salita",
  "codPostal": "3000"
}

### DELETE
DELETE http://localhost:3000/api/localidad/{{id}}
