### GET ALL
GET http://localhost:3000/api/centroAtencion

### POST
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/centroAtencion   
Content-Type: application/json 

{
  "nombre": "Error",
  "domicilio": "-",
  "localidad": 4
}

### ID
@id = 10

### GET ONE 
GET http://localhost:3000/api/centroAtencion/{{id}}

### PUT
PUT http://localhost:3000/api/centroAtencion/{{id}}
Content-Type: application/json

{
  "domicilio": "Zuviría 55"
}

### DELETE
DELETE http://localhost:3000/api/centroAtencion/{{id}}
