### GET ALL
GET http://localhost:3000/api/usuario

### POST
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/usuario
Content-Type: application/json

{
  "email": "admin",
  "contraseña": "12",
  "role": "admin"
}
### LOGIN
POST http://localhost:3000/api/usuario/login
Content-Type: application/json

{
  "email": "admin",
  "contraseña": "12"
}

### ID
@id = 2

### GET ONE 
GET http://localhost:3000/api/paciente/{{id}}

### PUT
PUT http://localhost:3000/api/paciente/{{id}}
Content-Type: application/json

{
  "nombre": "Santiago",
  "apellido": "Dedich",
  "dni": "12345678",
  "fechaNacimiento": "2003-01-01",
  "telefono": "123456789",
  "email": "santiago@example.com",
  "direccion": "Calle Falsa 123"
}

### DELETE
DELETE http://localhost:3000/api/paciente/{{id}}
